name: iOS App Deploy with Fastlane

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        # Fixed: Remove cache-dependency-path since package-lock.json is in root
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        working-directory: ios/App
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Install Capacitor CLI
      run: |
        npm install -g @capacitor/cli
        
    - name: Build React app
      run: |
        npm run build
        
    - name: Add iOS platform (if not exists)
      run: |
        npx cap add ios || echo "iOS platform already exists"
        
    - name: Sync Capacitor
      run: |
        npx cap sync ios
        
    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        pod install
        
    - name: Create App Store Connect API Key
      run: |
        mkdir -p ~/private_keys
        echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" | base64 -d > ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
        
    - name: Install Fastlane dependencies
      run: |
        cd ios/App
        bundle install
        
    - name: Build and Deploy with Fastlane
      run: |
        cd ios/App
        bundle exec fastlane beta
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_PATH: ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
        TEAM_ID: ${{ secrets.TEAM_ID }}
        
    - name: Cleanup
      if: always()
      run: |
        rm -f ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
      if: always()
      run: |
        rm -f ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
